

###########################################################
library(EasyABC) # contains ABC algorithms in R
###########################################################
source("SIR_model.R") # source file containing model to be used
###########################################################

# 1. Rejection ABC set up for scenario 2

set.seed(121) # set seed for reproducibility

ABC_rej3 <- ABC_rejection(model = modelforABC, # SIR model 
                          prior = list(c("unif",0,1), # define prior distribution for beta
                                       c("unif",0,0.5)), # define prior distribution for gamma
                          summary_stat_target = c(0.622, 0.371, 0.677),# a vector of target statistics
                          nb_simul = 75000, # number of simulations to perform
                          tol = 1, # tolerance allowed (tol=1, retain all parameter combinations draen from the prior)
                          progress_bar = T, # show simulation progress
                          verbose = T)# save intermediate results to current directory

#########################################################
#get desired size of posterior

abcrej <- abc(target = c(0.622, 0.371, 0.677), # target statistics
              param = ABC_rej3$param, # parameter combinations drawn from prior
              sumstat = ABC_rej3$stats, # summary statistics of generated by model
              tol = 0.07, # proportion of parameter combination to save as posterior
              method = "rejection") # ABC method used


